### PR TITLE
Fixed anon draft crash

### LINKED ISSUE #701: Anonymous draft submission fails with an HTTP 500
**Describe the bug**
After drafting the last card of a draft anonymously `/cube/submitdeck/:id` redirects to a 500 error message page.

**To Reproduce**
1. Anonymously draft a user's cube.
2. Make the final pick of the draft.
3. Page redirects to `/cube/submitdeck/:id`
4. A white page with a json object is displayed. HTTP status 500.

```json
{
  "success": "false",
  "message": {}
}
```

### PR DESCRIPTION
**Pull request by dekkerglen**
fixes #701

### CODE REVIEW

File: routes/cube_routes.js [hunk 1]
```diff
@@ -2482,14 +2482,22 @@ router.post('/submitdeck/:id', async (req, res) => {
     const userq = User.findById(deck.owner);
     const cubeOwnerq = User.findById(cube.owner);
 
-    const [user, cubeOwner] = await Promise.all([userq, cubeOwnerq]);
+    var [user, cubeOwner] = await Promise.all([userq, cubeOwnerq]);
```
Comment (haganbmj) [inline routes/cube_routes.js]: There isn't a strong reason to use `var` over `let` in es6 as a heads up. `let` does allow for reassignment.
