### PR TITLE
Fetch price data for all card versions to display in CardModal

### LINKED ISSUE #607: The price in card view disappears when you change version.
**Describe the bug**
The box containing price of a card in the card view disapears if you change the version of the card from the drop down.

**To Reproduce**
1. click on any card that have multiple versions
2. click the version selector drop down and select a different version
3. the price displayed below the card image disappears.
**Screenshots**
image

image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: laptop
 - OS: win 10
 - Browser chrome

**Additional context**

### PR DESCRIPTION
**Pull request by anderoonies**
fixes #607 

`getversions` fetches price data, which is passed into the card modal so version changes have access to prices

unable to test this fully locally because i don't have access to the tcgplayer api, but if someone who does could test this that would be great 🙇

### CODE REVIEW

File: routes/cube_routes.js [hunk 1]
```diff
@@ -2572,10 +2591,11 @@ router.post('/api/getversions', function(req, res) {
   req.body.forEach(function(cardid, index) {
     cards[cardid] = [];
     carddb.nameToId[carddb.cardFromId(cardid).name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")].forEach(function(id, index) {
+      const card = carddb.cardFromId(id);
       cards[cardid].push({
         id: id,
-        version: carddb.cardFromId(id).full_name.toUpperCase().substring(carddb.cardFromId(id).full_name.indexOf('[') + 1, carddb.cardFromId(id).full_name.indexOf(']')),
-        img: carddb.cardFromId(id).image_normal
+        version: card.full_name.toUpperCase().substring(carddb.cardFromId(id).full_name.indexOf('[') + 1, card.full_name.indexOf(']')),
+        img: card.image_normal,
```
Comment (anderoonies) [inline routes/cube_routes.js]: just saving some `.cardFromId` calls here

File: routes/cube_routes.js [hunk 2]
```diff
@@ -2557,13 +2557,32 @@ router.get('/api/getcardfromid/:id', function(req, res) {
 
 router.get('/api/getversions/:id', function(req, res) {
   cards = [];
+  tcg = [];
   carddb.nameToId[carddb.cardFromId(req.params.id).name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")].forEach(function(id, index) {
```
Comment (phulin) [inline routes/cube_routes.js]:
```suggestion
  carddb.allIds(req.params.id).forEach(function(id, index) {
```

Comment (anderoonies) [reply routes/cube_routes.js]: cool! didnt know that existed
