### PR TITLE
Bulk Upload fix

### LINKED ISSUE #2145: +2 Mace causing issues
he new AFR card name "+2 Mace" is causing some problems in CubeCobra.  First, I notice that the "Paste" option for adding cards didn't like "2x +2 Mace", interpreting it as 4 "Mace" cards.

Next, when trying to quick filter this list (https://cubecobra.com/cube/list/afr-artisan-doubleton) on the word "token", I get the error message:

Invalid regular expression: /+2 Mace/: Nothing to repeat

### PR DESCRIPTION
**Pull request by lunakv**
Fixes #2145 (along with #2147).

The current logic for parsing bulk upload TXT files is some wild stuff. This PR rewrites it to simplify things and fix some issues. For instance, instead of pushing objects into an array we're currently iterating through (which is a no-no) and then doing some weird shenanigans to determine card counts and set codes, the code now does only one pass through the input list, splits it with a single regex, then chooses the appropriate version. Just be glad no one tried to bulk upload "Borrowing 100,000 Arrows" before now.

Aside from bugfixes, the only functional changes in this PR are that set codes now ignore case, and that missing cards are displayed as the whole line, instead of weirdly split. I also changed `missing` to be an array instead of a string, since we were stringifying elements into it only to split them again on render.

### CODE REVIEW

**Review by dekkerglen — DISMISSED** [review]

File: routes/cube/helper.js [hunk 1]
```diff
@@ -74,58 +74,58 @@ async function updateCubeAndBlog(req, res, cube, changelog, added, missing) {
...
-            count = 1;
-          }
-          for (let j = 0; j < count; j += 1) {
-            cards.push(numericMatch[2]);
+        // separate counts and sets from the name
+        //                              |    count?   |name|     (set)?      |
+        const splitLine = item.match(/^(?:([0-9]+)x? )?(.*?)(?: \(([^)(]+)\))?$/);
+        const name = splitLine[2];
+        const set = splitLine[3];
+        let count = parseInt(splitLine[1], 10);
```
Comment (ruler501) [inline routes/cube/helper.js:100]: There's toNullableInt you could use here so it's just `toNullableInt(splitLine[1]) ?? 1`.

**Review by ruler501 — APPROVED** [review]

File: src/pages/BulkUploadPage.js [hunk 2]
```diff
@@ -60,7 +60,7 @@ const BulkUploadPageRaw = ({ cubeID, missing, blogpost, cube }) => {
           </p>
           <Row>
             <Col>
-              {missing.split('\n').map((card, index) => (
+              {missing.map((card, index) => (
```
Comment (ruler501) [inline src/pages/BulkUploadPage.js:63]: Update propTypes with the new type.

**Review by ruler501 — CHANGES_REQUESTED** [review]

File: routes/cube/helper.js (hunk 1 above)
Comment (lunakv) [reply routes/cube/helper.js:100]: can't use `??` yet.
