### PR TITLE
Validate colors on CSV upload.

### LINKED ISSUE #446: Context Modal Broken
On development, individual card context modal is broken, does not open, and hides the view.

On 2.1, the context modal doesn't work for lands specifically. Doesn't open modal.

### PR DESCRIPTION
**Pull request by phulin**
Fixes #446

### CODE REVIEW

File: one_shot_scripts/validate_colors.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+const mongoose = require('mongoose');
+const Cube = require('../models/cube');
+const config = require('../config/database');
+
```
Comment (dekkerglen) [inline one_shot_scripts/validate_colors.js]: This script will OOM on live server. Can't load all cubes into memory at once.

Comment (phulin) [reply one_shot_scripts/validate_colors.js]: Will fix
