### PR TITLE
1123 draft should allow cmc null

### LINKED ISSUE #1123: Cards that appear more than once in playtest mode can't be picked.
**Describe the bug**
In playtest mode, multiples of the same card appearing in a pack result in neither being pickable due to a JS error:
`Util.js:83 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of null
    at d (Util.js:83)
    at CubeDraftPage.js:170
    at Object.Bi (react-dom.production.min.js:175)
    at Ai (react-dom.production.min.js:14)
    at Di (react-dom.production.min.js:14)
    at wf (react-dom.production.min.js:14)
    at Ei (react-dom.production.min.js:176)
    at zd (react-dom.production.min.js:15)
    at uc (react-dom.production.min.js:15)
    at aj (react-dom.production.min.js:41)`

**To Reproduce**
1. Go to [https://cubecobra.com/cube/draft/5e4e88db18368406b4324502](https://cubecobra.com/cube/draft/5e4e88db18368406b4324502)
2. Pick any card (I picked Grusilda) followed by either copy of Watermarket.

**Expected behavior**
Watermarket should be picked.

**Desktop (please complete the following information):**
 - OS: W10
 - Chrome 80.0.3987.106 (64-bit)

### PR DESCRIPTION
**Pull request by gabyreilly**
fixes #1123 but we might want some follow up work, i opened https://github.com/dekkerglen/CubeCobra/issues/1133 for later discussion.

In the reported issue, both cards that were undraftable had CMC `null` instead of 0 as expected.

On my local database, the cards initially had CMC zero, but I could reproduce this issue using bulk edit:

image

This quick-fix allows CMC `null` cards to be drafted, and places them in the 0 CMC column.

### CODE REVIEW

File: src/utils/Draft.js [hunk 1]
```diff
@@ -79,7 +79,7 @@ function botPicks() {
     const ratedPicks = [];
     const unratedPicks = [];
     for (let cardIndex = 0; cardIndex < botPack.length; cardIndex++) {
-      if (draft.ratings[botPack[cardIndex].details.name]) {
+      if (draft.ratings && draft.ratings[botPack[cardIndex].details.name]) {
```
Comment (gabyreilly) [inline src/utils/Draft.js]: This isn't related to the filed issue, but it caused some problems for me locally because the draft didn't have ratings.

Comment (dekkerglen) [reply src/utils/Draft.js]: This happens b/c you don't have enough draft data in your local DB - and mongoose just saves the empty dict as null. This change is fine, just wanted to share why this is happening
