### PR TITLE
Fix draft format delete.

### LINKED ISSUE #1054: Deleting custom draft formats is broken.

### PR DESCRIPTION
**Pull request by phulin**
Fixes #1054

### CODE REVIEW

File: routes/cube_routes.js [hunk 1]
```diff
@@ -3087,23 +3087,25 @@ router.delete('/blog/remove/:id', ensureAuth, async (req, res) => {
...
-    const id = parseInt(req.params.id.split(';')[1], 10);
-
+    const { cubeid, index } = req.params;
     const cube = await Cube.findOne(build_id_query(cubeid));
-    if (!cube || cube.owner !== req.user.id || !Number.isInteger(id) || id < 0 || id >= cube.draft_formats.length) {
-      return res.sendStatus(401);
+    if (!cube || !req.user._id.equals(cube.owner) || index < 0 || index >= cube.draft_formats.length) {
+      return res.status(401).send({
+        success: 'false',
+        message: 'Invalid request.',
```
Comment (ruler501) [inline routes/cube_routes.js]: This should say Not authorized to match the status code.
