### PR TITLE
Fix issues with csv export

### LINKED ISSUE #1390: CSV download spins forever
https://cubecobra.com/cube/list/patrick -> Export CSV

### PR DESCRIPTION
**Pull request by dekkerglen**
Fixes #1390

Also adds null checks to the rarity and colorcategory fields

### CODE REVIEW

**Comment by phulin** [comment]
CI failing

File: routes/cube_routes.js [hunk 1]
```diff
@@ -1468,11 +1468,11 @@ function writeCard(res, card, maybe) {
   res.write(`"${name}",`);
   res.write(`${card.cmc},`);
   res.write(`"${card.type_line.replace('—', '-')}",`);
-  res.write(`${card.colors.join('')},`);
+  res.write(`${(card.colors || []).join('')},`);
   res.write(`"${carddb.cardFromId(card.cardID).set}",`);
   res.write(`"${carddb.cardFromId(card.cardID).collector_number}",`);
-  res.write(`${card.rarity},`);
-  res.write(`${card.colorCategory},`);
+  res.write(`${card.rarity && card.rarity !== 'undefined' ? card.rarity : rarity},`);
```
Comment (phulin) [inline routes/cube_routes.js:1474]:
```suggestion
  res.write(`${card.rarity && card.rarity !== undefined ? card.rarity : rarity},`);
```

Comment (dekkerglen) [reply routes/cube_routes.js:1474]: No, we need to check for the string undefined, that was the issue. Somehow this field has gotten into this bad state
